# source files
SOURCES = fw.c \
          logic16.c \
          fpga.c \
          gpif_stuff.c \
          debug_i2c.c

# usb descriptos
A51_SOURCES = dscr.a51

# output name
BASENAME = logic16

# SDCCFLAGS += -DDEBUG

# use fx2lib
include fx2lib/lib/fx2.mk
